# GoReleaser v2 configuration
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.Version={{ .Tag }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm

archives:
  - format: tar.gz
    replacements:
      darwin: MacOs
      linux: Linux
      windows: Windows
      amd64: x86_64
      "386": x86

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "version"
